Return-Path: <linux-block-owner@vger.kernel.org>
X-Original-To: lists+linux-block@lfdr.de
Delivered-To: lists+linux-block@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [209.132.180.67])
	by mail.lfdr.de (Postfix) with ESMTP id 181C614CDC3
	for <lists+linux-block@lfdr.de>; Wed, 29 Jan 2020 16:46:26 +0100 (CET)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S1726708AbgA2PqZ (ORCPT <rfc822;lists+linux-block@lfdr.de>);
        Wed, 29 Jan 2020 10:46:25 -0500
Received: from mx2.suse.de ([195.135.220.15]:37320 "EHLO mx2.suse.de"
        rhost-flags-OK-OK-OK-OK) by vger.kernel.org with ESMTP
        id S1726564AbgA2PqZ (ORCPT <rfc822;linux-block@vger.kernel.org>);
        Wed, 29 Jan 2020 10:46:25 -0500
X-Virus-Scanned: by amavisd-new at test-mx.suse.de
Received: from relay2.suse.de (unknown [195.135.220.254])
        by mx2.suse.de (Postfix) with ESMTP id C3D8EAD31;
        Wed, 29 Jan 2020 15:46:23 +0000 (UTC)
From:   Daniel Wagner <dwagner@suse.de>
To:     linux-block@vger.kernel.org
Cc:     Elliott@suse.de, Robert <elliott@hpe.com>,
        Johannes Thumshirn <Johannes.Thumshirn@wdc.com>,
        Logan Gunthorpe <logang@deltatee.com>,
        Omar Sandoval <osandov@fb.com>, Daniel Wagner <dwagner@suse.de>
Subject: [PATCH blktests v2 1/2] nvme/018: Ignore message generated by nvme read
Date:   Wed, 29 Jan 2020 16:46:18 +0100
Message-Id: <20200129154619.103332-2-dwagner@suse.de>
X-Mailer: git-send-email 2.16.4
In-Reply-To: <20200129154619.103332-1-dwagner@suse.de>
References: <20200129154619.103332-1-dwagner@suse.de>
Sender: linux-block-owner@vger.kernel.org
Precedence: bulk
List-ID: <linux-block.vger.kernel.org>
X-Mailing-List: linux-block@vger.kernel.org

nvme-cli writes 'CAP_EXCEEDED' message also on stdout not just
stderr. This lets the test fail as well.

Fixes: 1aee5f430b30 ("nvme/018: Ignore error message generated by nvme read")
Signed-off-by: Daniel Wagner <dwagner@suse.de>
Reviewed-by: Logan Gunthorpe <logang@deltatee.com>
---
 tests/nvme/018 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/tests/nvme/018 b/tests/nvme/018
index 0a5b4c2ab019..d0f15db23538 100755
--- a/tests/nvme/018
+++ b/tests/nvme/018
@@ -43,7 +43,7 @@ test() {
 	sectors="$(blockdev --getsz "/dev/${nvmedev}n1")"
 	bs="$(blockdev --getbsz "/dev/${nvmedev}n1")"
 
-	nvme read "/dev/${nvmedev}n1" -s "$sectors" -c 0 -z "$bs" 2>"$FULL" \
+	nvme read "/dev/${nvmedev}n1" -s "$sectors" -c 0 -z "$bs" &>"$FULL" \
 		&& echo "ERROR: Successfully read out of device lba range"
 
 	nvme disconnect -n "${subsys_name}"
-- 
2.16.4

