Return-Path: <linux-block-owner@vger.kernel.org>
X-Original-To: lists+linux-block@lfdr.de
Delivered-To: lists+linux-block@lfdr.de
Received: from out1.vger.email (out1.vger.email [IPv6:2620:137:e000::1:20])
	by mail.lfdr.de (Postfix) with ESMTP id 7A11E6F7E5E
	for <lists+linux-block@lfdr.de>; Fri,  5 May 2023 10:06:59 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S231446AbjEEIG5 (ORCPT <rfc822;lists+linux-block@lfdr.de>);
        Fri, 5 May 2023 04:06:57 -0400
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:45668 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S230322AbjEEIG5 (ORCPT
        <rfc822;linux-block@vger.kernel.org>); Fri, 5 May 2023 04:06:57 -0400
Received: from mail-io1-f69.google.com (mail-io1-f69.google.com [209.85.166.69])
        by lindbergh.monkeyblade.net (Postfix) with ESMTPS id A6277E4B
        for <linux-block@vger.kernel.org>; Fri,  5 May 2023 01:06:52 -0700 (PDT)
Received: by mail-io1-f69.google.com with SMTP id ca18e2360f4ac-7696bf2c54eso196390039f.3
        for <linux-block@vger.kernel.org>; Fri, 05 May 2023 01:06:52 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20221208; t=1683274012; x=1685866012;
        h=to:from:subject:message-id:date:mime-version:x-gm-message-state
         :from:to:cc:subject:date:message-id:reply-to;
        bh=TeSUPZJHLmHu4GxXGL1I+J0K+4NIwj6BUxF5QRXN0fI=;
        b=Qb60o5tht0tRhEJu3QSzX9IMTLRDHQKMZanMo9xqSWvTwbyhdA4DphZ+JEvX0mxERL
         qeG6ksp5uHMUxuVSNnbnA7kuS0PXV5ur6yM+DuJBTqv4Hh0w/WP8DETHgGOCw8cX+Xn4
         LGo7jqdIcu4Y7lKXUMsBQ56SKLBKbtwKkep9Dsblu9xC9R8xcDuYZe8kYq3P870iB45m
         vPd//c9mGj0QsbIHSQtbQLjYnwhXGc8c2+8ElYq53jTu8y9+Br6uApKOKRr2aXxWlFT6
         XDucdX+9Cquxq5wv6/8jciIXVNDAn1HqUCSgjC/hUHjBWzrrnoH6yNDOWtPmlvVElwVt
         QJaA==
X-Gm-Message-State: AC+VfDzumXv62U34pF5PuPd/rA4cn/KrTt/73DVqsKtv21kpSlTg0n1o
        AfLrZOPnEP3qI7J9ffxmYYTrMizM/0iawgLjxZ0OEDIDfI0yNE4=
X-Google-Smtp-Source: ACHHUZ5wZ6532/pMP+Qv5iqCEjQDIev11sib/BVfz5w42LFgq7uJRbqLCNWQB2uC03t2B1WrLQ/UpVF+Iaw4rMQjqNjjT6z/90S/
MIME-Version: 1.0
X-Received: by 2002:a6b:d102:0:b0:759:25eb:210d with SMTP id
 l2-20020a6bd102000000b0075925eb210dmr183833iob.0.1683274012052; Fri, 05 May
 2023 01:06:52 -0700 (PDT)
Date:   Fri, 05 May 2023 01:06:52 -0700
X-Google-Appengine-App-Id: s~syzkaller
X-Google-Appengine-App-Id-Alias: syzkaller
Message-ID: <0000000000008c534305faedc5ce@google.com>
Subject: [syzbot] Monthly block report (May 2023)
From:   syzbot <syzbot+listce23541c780281f050fb@syzkaller.appspotmail.com>
To:     linux-block@vger.kernel.org, linux-kernel@vger.kernel.org,
        syzkaller-bugs@googlegroups.com
Content-Type: text/plain; charset="UTF-8"
X-Spam-Status: No, score=-1.7 required=5.0 tests=BAYES_00,FROM_LOCAL_HEX,
        HEADER_FROM_DIFFERENT_DOMAINS,RCVD_IN_DNSWL_NONE,RCVD_IN_MSPIKE_H2,
        SPF_HELO_NONE,SPF_PASS,T_SCC_BODY_TEXT_LINE autolearn=no
        autolearn_force=no version=3.4.6
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
        lindbergh.monkeyblade.net
Precedence: bulk
List-ID: <linux-block.vger.kernel.org>
X-Mailing-List: linux-block@vger.kernel.org

Hello block maintainers/developers,

This is a 31-day syzbot report for the block subsystem.
All related reports/information can be found at:
https://syzkaller.appspot.com/upstream/s/block

During the period, 9 new issues were detected and 0 were fixed.
In total, 28 issues are still open and 81 have been fixed so far.

Some of the still happening issues:

Ref Crashes Repro Title
<1> 392     Yes   WARNING in copy_page_from_iter
                  https://syzkaller.appspot.com/bug?extid=63dec323ac56c28e644f
<2> 359     Yes   INFO: task hung in blkdev_put (4)
                  https://syzkaller.appspot.com/bug?extid=9a29d5e745bd7523c851
<3> 78      Yes   INFO: task hung in blkdev_fallocate
                  https://syzkaller.appspot.com/bug?extid=39b75c02b8be0a061bfc
<4> 33      Yes   INFO: task hung in nbd_add_socket (2)
                  https://syzkaller.appspot.com/bug?extid=cbb4b1ebc70d0c5a8c29
<5> 21      Yes   WARNING in blk_register_tracepoints
                  https://syzkaller.appspot.com/bug?extid=c54ded83396afee31eb1
<6> 7       No    WARNING in wait_til_done (2)
                  https://syzkaller.appspot.com/bug?extid=9bc4da690ee5334f5d15
<7> 2       No    WARNING in floppy_interrupt (2)
                  https://syzkaller.appspot.com/bug?extid=aa45f3927a085bc1b242

---
This report is generated by a bot. It may contain errors.
See https://goo.gl/tpsmEJ for more information about syzbot.
syzbot engineers can be reached at syzkaller@googlegroups.com.

To disable reminders for individual bugs, reply with the following command:
#syz set <Ref> no-reminders

To change bug's subsystems, reply with:
#syz set <Ref> subsystems: new-subsystem

You may send multiple commands in a single email message.
